version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Uncomment and set your GitHub token if you have one
      # - GITHUB_TOKEN=your_token_here
    volumes:
      - .:/app
    restart: unless-stopped
